// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Story
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string StoryUrl { get; set; }

    public DateTime Created { get; set; }

    public DateTime Modified { get; set; }
}